### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by yadferhad** [4e6anenk0/settings_provider#1]
I am getting the following init error from main():

flutter: SettingsModel init error: type 'Null' is not a subtype of type 'Object'
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Error initializing settings model. Model: PrintSettings. null

**Comment by yadferhad** [comment]
It seems as though the issue is coming from having nullable properties, is this not allowed?

**Comment by 4e6anenk0** [comment]
Thank you for trying out the library and sharing your experience. Yes, you are right about nullable values in properties. This is not intended. Perhaps it should have been mentioned in the description. All classes inheriting from `BaseProperty` should use actual values for settings and should not have `null` values. If a value is `null`, it means the absence of such setting. For example, as for default values, you can use things like empty strings `""` or `0`
